### ISSUE TITLE
Accidental Branch Creation

### ISSUE THREAD

**Issue by silabs-robin** [openhwgroup/cv32e40x-dv#51]
I accidentally added the wrong remote and pushed to create this branch (screenshot below).
Can I have the normal commiter's merge permissions without having direct write access?

(I don't have the permissions to delete that accidental branch.)

![bilde](https://github.com/openhwgroup/cv32e40x-dv/assets/75431602/b6d6faee-82c5-4483-aa83-ed800f2e0476)

**Comment by MikeOpenHWGroup** [comment]
> Can I have the normal commiter's merge permissions without having direct write access?

I am not sure.  AFAIK, Committers have write access to a repo and write access implies the ability to push directly to a  repo.

**Comment by silabs-robin** [comment]
> > Can I have the normal commiter's merge permissions without having direct write access?
> 
> I am not sure. AFAIK, Committers have write access to a repo and write access implies the ability to push directly to a repo.

Be that as it may.
I created this follow-up ticket: https://github.com/openhwgroup/cv32e40x-dv/issues/53
